;====================================================================
; Main.asm file generated by New Project wizard
;
; Created:   Tue Nov 29 2022
; Processor: 80C51
; Compiler:  ASEM-51 (Proteus)
;====================================================================

$NOMOD51
$INCLUDE (8051.MCU)

;====================================================================
; DEFINITIONS
;====================================================================

;====================================================================
; VARIABLES
;====================================================================

;====================================================================
; RESET and INTERRUPT VECTORS
;====================================================================

      ; Reset Vector
      org   0000h
      jmp   Start

;====================================================================
; CODE SEGMENT
;====================================================================

      org   0100h
Start:
      mov     P2,#0FFh  ;Seta P2 como entrada de dados
      mov     SCON,#50H
      mov     TMOD,#20H
      mov     TH1,#-3
      setb    TR1

Aux1: 
      jnb     RI,Aux1   ;Aguarda pela recepção do byte
      clr     RI        ;Limpa a flag de recepção
      mov     A,SBUF    ;Lê o byte lido
      mov     P1,A      ;Salva em P1
      mov     A,P2      ;Lê o valor em P2
      mov     SBUF,A    ;Transmite o valor de P2
Aux2:
      jnb     TI,Aux2   ;Aguarda a transmissão finalizar
      clr     TI        ;Limpa flag de transmissão
      jmp     Aux1      ;Retorna para receber próximo byte

Loop:	
      jmp Loop

;====================================================================
      END
